name: Yukyung Kim
bio: 'A designer from South Korea'
picture: 'assets/images/yukyung-profile.jpg'

# url: http://yukyungkim.github.io/
# your url: http://USERNAME.github.io/
permalink: /:title/

analytics: 'UA-MYANALYTICS'
facebook: ukyung.kim.9
instagram: yukyokie
linkedin: yukyungkim
github: you2530
email: you2530@gmail.com
behance: yukyungkim

exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor]

gems:
  - jemoji
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com
